# See options here = https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
gui:
  screenMode: "half"
  showRandomTip: false
  mainPanelSplitMode: "horizontal"
  expandFocusedSidePanel: true
  showFileTree: true
git:
  autoFetch: false
  fetchAll: false # only fetch current branch
  # paging:
  #   colorArg: always
  #   pager: delta --dark --paging=never --syntax-theme base16-256
  commit:
    autoWrapCommitMessage: false
os:
  editPreset: "nvim"
notARepository: "quit"
quitOnTopLevelReturn: true
